In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
df=pd.read_csv('50_Startups.csv')

In [4]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [6]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [7]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [13]:
df['State'] = df['State'].map({'New York':0,'California':1,'Florida':2}).astype(int)

In [15]:
df['State'].value_counts()

State
0    17
1    17
2    16
Name: count, dtype: int64

In [16]:
X=df.iloc[: ,:-1]
y=df.iloc[ : , -1]


In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train,X_test,y_train,y_test=sklearn.model_selection.train_test_split(X,y,test_size=0.2,random_state=1)

In [19]:
X_train

R&D Spend  Administration  Marketing Spend  State
32   63408.86       129219.61         46085.25      1
39   38558.51        82982.09        174999.30      1
21   78389.47       153773.43        299737.29      0
36   28663.76       127056.21        201126.82      2
19   86419.70       153514.11             0.00      0
42   23640.93        96189.63        148001.11      1
49       0.00       116983.80         45173.06      1
26   75328.87       144135.98        134050.07      2
22   73994.56       122782.75        303319.26      2
13   91992.39       135495.07        252664.93      1
41   27892.92        84710.77        164470.71      2
17   94657.16       145077.58        282574.31      0
45    1000.23       124153.04          1903.93      0
24   77044.01        99281.34        140574.81      0
23   67532.53       105751.03        304768.73      2
4   142107.34        91391.77        366168.42      2
33   55493.95       103057.49        214634.81      2
14  119943.24       156547.42        256512.92      2
30   61994.48       115641.28         91131.24      2
10  101913.08       110594.11        229160.95      2
28   66051.52       182645.56        118148.20      2
44   22177.74       154806.14         28334.72      1
34   46426.07       157693.92        210797.67      1
18   91749.16       114175.79        294919.57      2
20   76253.86       113867.30        298664.47      1
25   64664.71       139553.16        137962.62      1
6   134615.46       147198.87        127716.82      1
7   130298.13       145530.06        323876.68      2
47       0.00       135426.92             0.00      1
1   162597.70       151377.59        443898.53      1
16   78013.11       121597.55        264346.06      1
0   165349.20       136897.80        471784.10      0
15  114523.61       122616.84        261776.23      0
5   131876.90        99814.71        362861.36      0
11  100671.96        91790.61        249744.55      1
9   123334.88       108679.17        304981.62      1
8   120542.52       148718.95        311613.29      0
12   93863.75       127320.38        249839.44      2
43   15505.73       127382.30         35534.17      0
37   44069.95        51283.14        197029.42      1

In [20]:
len(X_train),len(y_train)

(40, 40)

In [21]:
len(X_test),len(y_test)

(10, 10)

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
lm=LinearRegression()

In [24]:
lm.fit(X_train,y_train)

LinearRegression()

**Traing Performance**

In [26]:
y_train_pred=lm.predict(X_train)
y_train_pred

array([ 98985.93327603,  83873.28876931, 117575.12515222,  76776.76439896,
       115082.57061532,  71416.19659812,  49929.54180198, 110840.17400213,
       114911.11320905, 127089.13138529,  75474.38383966, 129755.59360661,
        49198.51976827, 112368.19691262, 110091.17296557, 169785.69134349,
        98164.34401058, 148866.66061678,  99502.35248924, 134491.74936526,
       102860.5904782 ,  66302.45932481,  90373.89963741, 128497.86026895,
       116415.85398097, 102543.02901776, 156383.21530373, 158943.49701797,
        48458.55365865, 187225.90216113, 116715.08179609, 190105.84064858,
       144736.28983823, 161317.21524898, 134102.38895242, 153125.88032268,
       150627.10068872, 128713.2949918 ,  61389.05651809,  89054.91601833])

In [27]:
Training_data_prediction=pd.DataFrame()
Training_data_prediction=X_train.copy()
Training_data_prediction['Actual Value']=y_train.copy()
Training_data_prediction['Predicted Value']=y_train_pred
Training_data_prediction

R&D Spend  Administration  Marketing Spend  State  Actual Value  \
32   63408.86       129219.61         46085.25      1      97427.84   
39   38558.51        82982.09        174999.30      1      81005.76   
21   78389.47       153773.43        299737.29      0     111313.02   
36   28663.76       127056.21        201126.82      2      90708.19   
19   86419.70       153514.11             0.00      0     122776.86   
42   23640.93        96189.63        148001.11      1      71498.49   
49       0.00       116983.80         45173.06      1      14681.40   
26   75328.87       144135.98        134050.07      2     105733.54   
22   73994.56       122782.75        303319.26      2     110352.25   
13   91992.39       135495.07        252664.93      1     134307.35   
41   27892.92        84710.77        164470.71      2      77798.83   
17   94657.16       145077.58        282574.31      0     125370.37   
45    1000.23       124153.04          1903.93      0      64926.08   
24   77044.01        99281.34        140574.81      0     108552.04   
23   67532.53       105751.03        304768.73      2     108733.99   
4   142107.34        91391.77        366168.42      2     166187.94   
33   55493.95       103057.49        214634.81      2      96778.92   
14  119943.24       156547.42        256512.92      2     132602.65   
30   61994.48       115641.28         91131.24      2      99937.59   
10  101913.08       110594.11        229160.95      2     146121.95   
28   66051.52       182645.56        118148.20      2     103282.38   
44   22177.74       154806.14         28334.72      1      65200.33   
34   46426.07       157693.92        210797.67      1      96712.80   
18   91749.16       114175.79        294919.57      2     124266.90   
20   76253.86       113867.30        298664.47      1     118474.03   
25   64664.71       139553.16        137962.62      1     107404.34   
6   134615.46       147198.87        127716.82      1     156122.51   
7   130298.13       145530.06        323876.68      2     155752.60   
47       0.00       135426.92             0.00      1      42559.73   
1   162597.70       151377.59        443898.53      1     191792.06   
16   78013.11       121597.55        264346.06      1     126992.93   
0   165349.20       136897.80        471784.10      0     192261.83   
15  114523.61       122616.84        261776.23      0     129917.04   
5   131876.90        99814.71        362861.36      0     156991.12   
11  100671.96        91790.61        249744.55      1     144259.40   
9   123334.88       108679.17        304981.62      1     149759.96   
8   120542.52       148718.95        311613.29      0     152211.77   
12   93863.75       127320.38        249839.44      2     141585.52   
43   15505.73       127382.30         35534.17      0      69758.98   
37   44069.95        51283.14        197029.42      1      89949.14   

    Predicted Value  
32     98985.933276  
39     83873.288769  
21    117575.125152  
36     76776.764399  
19    115082.570615  
42     71416.196598  
49     49929.541802  
26    110840.174002  
22    114911.113209  
13    127089.131385  
41     75474.383840  
17    129755.593607  
45     49198.519768  
24    112368.196913  
23    110091.172966  
4     169785.691343  
33     98164.344011  
14    148866.660617  
30     99502.352489  
10    134491.749365  
28    102860.590478  
44     66302.459325  
34     90373.899637  
18    128497.860269  
20    116415.853981  
25    102543.029018  
6     156383.215304  
7     158943.497018  
47     48458.553659  
1     187225.902161  
16    116715.081796  
0     190105.840649  
15    144736.289838  
5     161317.215249  
11    134102.388952  
9     153125.880323  
8     150627.100689  
12    128713.294992  
43     61389.056518  
37     89054.916018

In [28]:
Training_data_prediction.shape

(40, 6)

In [30]:
#alog   y=m1x1+m2x2+m3x3+m4x4+c

lm.coef_ # m values

array([ 7.74878648e-01, -8.52492210e-03,  2.90828645e-02,  1.86571447e+02])

In [31]:
# c value
lm.intercept_

49426.486154142236

In [32]:
from sklearn.metrics import mean_squared_error,r2_score

In [33]:
mean_squared_error(y_train,y_train_pred)

80079540.61681831

In [34]:
r2_score(y_train,y_train_pred)

0.9424169581402101

**Training Data Performance**

**Normal Calculations**

In [35]:
Training_data_prediction.index

Index([32, 39, 21, 36, 19, 42, 49, 26, 22, 13, 41, 17, 45, 24, 23,  4, 33, 14,
       30, 10, 28, 44, 34, 18, 20, 25,  6,  7, 47,  1, 16,  0, 15,  5, 11,  9,
        8, 12, 43, 37],
      dtype='int64')

**Mean_square_error calculation**

In [37]:
#mean_square_error
count=0
for i in Training_data_prediction.index:
  count=count + (Training_data_prediction['Actual Value'][i]-Training_data_prediction['Predicted Value'][i])**2
print(count/len(Training_data_prediction))

80079540.61681828


**r2_score Calculation**

In [38]:
y_train.index

Index([32, 39, 21, 36, 19, 42, 49, 26, 22, 13, 41, 17, 45, 24, 23,  4, 33, 14,
       30, 10, 28, 44, 34, 18, 20, 25,  6,  7, 47,  1, 16,  0, 15,  5, 11,  9,
        8, 12, 43, 37],
      dtype='int64')

In [54]:
y_train.shape

(40,)

In [40]:
sum(y_train)

4582070.43

In [55]:
#y_train -> sum of y_train or mean of y_train
count=0
for i in Training_data_prediction.index:
  count=count+Training_data_prediction['Actual Value'][i]
print(count)


4582070.43


In [61]:
#r2_score
sum=4582070.43
count=0
for i in Training_data_prediction.index:
  count=count+((Training_data_prediction['Actual Value'][i]-Training_data_prediction['Predicted Value'][i]**2)/(Training_data_prediction['Actual Value'][i]-sum**2))
print(1-count)


0.9725032871118193


In [42]:
r2_score(y_train,y_train_pred)

0.9424169581402101

In [62]:
lm.coef_

array([ 7.74878648e-01, -8.52492210e-03,  2.90828645e-02,  1.86571447e+02])

In [63]:
lm.intercept_l

49426.486154142236

**Alogorithm:

 is y=m1x1+m2x2+m3x3+m4x4+c**

In [64]:
m1,m2,m3,m4=lm.coef_

In [67]:
c=lm.intercept_

In [74]:
Training_data_prediction

R&D Spend  Administration  Marketing Spend  State  Actual Value  \
32   63408.86       129219.61         46085.25      1      97427.84   
39   38558.51        82982.09        174999.30      1      81005.76   
21   78389.47       153773.43        299737.29      0     111313.02   
36   28663.76       127056.21        201126.82      2      90708.19   
19   86419.70       153514.11             0.00      0     122776.86   
42   23640.93        96189.63        148001.11      1      71498.49   
49       0.00       116983.80         45173.06      1      14681.40   
26   75328.87       144135.98        134050.07      2     105733.54   
22   73994.56       122782.75        303319.26      2     110352.25   
13   91992.39       135495.07        252664.93      1     134307.35   
41   27892.92        84710.77        164470.71      2      77798.83   
17   94657.16       145077.58        282574.31      0     125370.37   
45    1000.23       124153.04          1903.93      0      64926.08   
24   77044.01        99281.34        140574.81      0     108552.04   
23   67532.53       105751.03        304768.73      2     108733.99   
4   142107.34        91391.77        366168.42      2     166187.94   
33   55493.95       103057.49        214634.81      2      96778.92   
14  119943.24       156547.42        256512.92      2     132602.65   
30   61994.48       115641.28         91131.24      2      99937.59   
10  101913.08       110594.11        229160.95      2     146121.95   
28   66051.52       182645.56        118148.20      2     103282.38   
44   22177.74       154806.14         28334.72      1      65200.33   
34   46426.07       157693.92        210797.67      1      96712.80   
18   91749.16       114175.79        294919.57      2     124266.90   
20   76253.86       113867.30        298664.47      1     118474.03   
25   64664.71       139553.16        137962.62      1     107404.34   
6   134615.46       147198.87        127716.82      1     156122.51   
7   130298.13       145530.06        323876.68      2     155752.60   
47       0.00       135426.92             0.00      1      42559.73   
1   162597.70       151377.59        443898.53      1     191792.06   
16   78013.11       121597.55        264346.06      1     126992.93   
0   165349.20       136897.80        471784.10      0     192261.83   
15  114523.61       122616.84        261776.23      0     129917.04   
5   131876.90        99814.71        362861.36      0     156991.12   
11  100671.96        91790.61        249744.55      1     144259.40   
9   123334.88       108679.17        304981.62      1     149759.96   
8   120542.52       148718.95        311613.29      0     152211.77   
12   93863.75       127320.38        249839.44      2     141585.52   
43   15505.73       127382.30         35534.17      0      69758.98   
37   44069.95        51283.14        197029.42      1      89949.14   

    Predicted Value  
32     98985.933276  
39     83873.288769  
21    117575.125152  
36     76776.764399  
19    115082.570615  
42     71416.196598  
49     49929.541802  
26    110840.174002  
22    114911.113209  
13    127089.131385  
41     75474.383840  
17    129755.593607  
45     49198.519768  
24    112368.196913  
23    110091.172966  
4     169785.691343  
33     98164.344011  
14    148866.660617  
30     99502.352489  
10    134491.749365  
28    102860.590478  
44     66302.459325  
34     90373.899637  
18    128497.860269  
20    116415.853981  
25    102543.029018  
6     156383.215304  
7     158943.497018  
47     48458.553659  
1     187225.902161  
16    116715.081796  
0     190105.840649  
15    144736.289838  
5     161317.215249  
11    134102.388952  
9     153125.880323  
8     150627.100689  
12    128713.294992  
43     61389.056518  
37     89054.916018

In [89]:
Training_data_prediction['Actual Value'][37]

89949.14

In [110]:
X_train.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State'], dtype='object')

**Calculate Predicted value using m,x,c values**


'one row of X_train data'

In [109]:
lm.coef_[0]*44069.95+lm.coef_[1]*51283.14+lm.coef_[2]*197029.42	+ lm.coef_[3]*1+lm.intercept_

89054.91601832892

**Testing Data Performance**

In [112]:
y_test_pred=lm.predict(X_test)
y_test_pred

array([114482.68730189,  90333.7866289 ,  75908.97116585,  69927.80233176,
       179699.82586154, 171430.45835272,  49405.40280247, 102074.07638902,
        58472.56632227,  98063.628483  ])

In [113]:
Testing_Data_predicted=pd.DataFrame()
Testing_Data_predicted=X_test.copy()
Testing_Data_predicted['Actual value']=y_test.copy()
Testing_Data_predicted['Predicted value']=y_test_pred
Testing_Data_predicted

R&D Spend  Administration  Marketing Spend  State  Actual value  \
27   72107.60       127864.55        353183.81      0     105008.31   
35   46014.02        85047.44        205517.64      0      96479.51   
40   28754.33       118546.05        172795.67      1      78239.91   
38   20229.59        65947.93        185265.10      0      81229.06   
2   153441.51       101145.55        407934.54      2     191050.39   
3   144372.41       118671.85        383199.62      0     182901.99   
48     542.05        51743.15             0.00      0      35673.41   
29   65605.48       153032.06        107138.38      0     101004.64   
46    1315.46       115816.21        297114.46      2      49490.75   
31   61136.38       152701.92         88218.23      0      97483.56   

    Predicted value  
27    114482.687302  
35     90333.786629  
40     75908.971166  
38     69927.802332  
2     179699.825862  
3     171430.458353  
48     49405.402802  
29    102074.076389  
46     58472.566322  
31     98063.628483

In [114]:
r2_score(y_test,y_test_pred)

0.9650991796290039

In [115]:
mean_squared_error(y_test,y_test_pred)

79183761.0750145